### ISSUE TITLE
class file has wrong version 55.0, should be 52.0 (alfresco-data-model-8.50.1.jar (AuthenticationException.class))

### ISSUE THREAD

**Issue by sumitt** [saidone75/alfresco-totp-authenticator#11]
Hi,

Can you please help me fixing the below error while compiling on Java 8?

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile

bad class file: /home/ev-developer/.m2/repository/org/alfresco/alfresco-data-model/8.50.1/alfresco-data-model-8.50.1.jar(org/alfresco/repo/security/authentication/AuthenticationException.class)
[ERROR]     class file has wrong version 55.0, should be 52.0

Thanks in advance.

**Comment by saidone75** [comment]
Hi @sumitt,

that jar comes with Alfresco SDK and is not under my control. I suggest you to use Java 11 or higher to build the AMP.
Please note that this project is born (an I tested it only) under Alfresco 6.2 which also require Java 11.
I'm pretty sure that switching to an older SDK will break everything.

Marco
