### ISSUE TITLE
Can you tell me in your video, which OTPAuth QR code reader you have used?

### ISSUE THREAD

**Issue by qgou** [saidone75/alfresco-totp-authenticator#14]
I have successfully installed your module onto my local Alfresco 7. I enabled TOTP settings for a new user under "My Profile". I got the QR code. Which tool should I use to scan the QR code and get the six digits number to put in login screen? When I used OTPAuth app from my iphone, I can scan the QR code and got 6 digit code, but when I enter into login screen, it still cannot login. My new user is dead in water now as far as login. Admin cannot reset it not to use TOTP. Thanks. This new user was able to login BEFORE enable TOT. Here is what shows on my iPhone
![IMG_4671](https://user-images.githubusercontent.com/1247862/136113023-4bfc458c-e130-4de4-a3c4-3203012d455b.jpg)
P.

**Comment by saidone75** [comment]
Hi Qing,

I tested it with [andOTP](https://play.google.com/store/apps/details?id=org.shadowice.flocke.andotp) but should work with any TOTP compliant tool.

I started working on a [way for admin to disable TOTP](https://github.com/saidone75/alfresco-totp-authenticator/issues/10), the API works but UI is still missing. If you are on the latest build you can disable TOTP for a given user by calling http://alfresco_host:8080/alfresco/s/security/setsecret?user={user}&secret= authenticating with admin credentials.

Another bit more complicated way would be to update the user by directly querying the database.
