### ISSUE TITLE
alfresco-totp-authenticator 1.0

### ISSUE THREAD

**Issue by Sai-1411** [saidone75/alfresco-totp-authenticator#85]
Hi,
I have downloaded **alfresco-totp-authenticator-platform-1.0.amp & alfresco-totp-authenticator-share-1.0.amp file for alfresco 6.2**.

This totp authenticator amp was working good but from past three days it is not working properly
I have used many applications to make it work properly like Microsoft Authenticator, andOTP , Google Authenticator etc

But i am getting only this --> **error: invalid token** 

For alfresco 6.2 i am using java version 11.0.16.1

Can i know what could be the issue

**Comment by saidone75** [comment]
Hi Sai,

assuming that the keys are still correct, usually this problem is due to the clocks not being synchronized between the server and the device running the authenticator.

**Comment by Sai-1411** [comment]
Thank you Sir, there was clock not being synchronised with my device and system
After changes it started working properly

**Comment by saidone75** [comment]
Glad to have helped you!
